In [265]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [266]:
df = sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [267]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [268]:
from sklearn.model_selection import train_test_split
X = df.drop('species',axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

# KNN

In [269]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [270]:
model_knn.score(X_test,y_test)

0.98

# SVC

In [271]:
from sklearn.svm import SVC
#model_svc = SVC(kernel='rbf', gamma='auto', C=30)
model_svc = SVC(kernel='rbf')
model_svc.fit(X_train,y_train)

SVC()

In [272]:
model_svc.score(X_test,y_test)

1.0

# lets use the Grid Search CV

model_svc

In [273]:
from sklearn.model_selection import GridSearchCV
Classifier = GridSearchCV(model_svc, {
    'gamma': ['auto'],
    'C': [1, 10, 20, 25, 30],
    'kernel': ['linear', 'rbf']
    }, 
    cv=5, return_train_score=False)

In [274]:
Classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 25, 30], 'gamma': ['auto'],
                         'kernel': ['linear', 'rbf']})

In [275]:
result = pd.DataFrame(Classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000886,0.000322,0.000719,0.000360,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002100,0.000942,0.001582,0.000411,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001179,0.000496,0.001027,0.000321,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
3,0.000685,0.000176,0.000581,0.000262,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.000510,0.000009,0.000419,0.000013,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,7
5,0.000531,0.000009,0.000443,0.000011,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
6,0.000637,0.000180,0.000436,0.000041,25,auto,linear,"{'C': 25, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,8
7,0.000537,0.000017,0.000420,0.000005,25,auto,rbf,"{'C': 25, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
8,0.000515,0.000011,0.000421,0.000018,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,8
9,0.000556,0.000017,0.000434,0.000028,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,8

In [276]:
result[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667
6       25       linear         0.960000
7       25          rbf         0.966667
8       30       linear         0.960000
9       30          rbf         0.960000

In [277]:
result.loc[[result['mean_test_score'].idxmax()]]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000886,0.000322,0.000719,0.00036,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1

In [278]:
result.nlargest(1, 'mean_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000886,0.000322,0.000719,0.00036,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1

In [279]:
result[result['mean_test_score'] == result['mean_test_score'].max()]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000886,0.000322,0.000719,0.000360,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1
1,0.002100,0.000942,0.001582,0.000411,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1
3,0.000685,0.000176,0.000581,0.000262,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.01633,1

model_knn

In [280]:
from sklearn.model_selection import GridSearchCV
Classifier2 = GridSearchCV(model_knn, {
    'algorithm': ['auto'],
    'n_neighbors': [5, 10, 15, 25],
    'metric': ['euclidean', 'manhattan', 'minkowski']
    }, 
    cv=5, return_train_score=False)

In [281]:
Classifier2.fit(X, y)
Classifier2

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [5, 10, 15, 25]})

In [282]:
result2 = pd.DataFrame(Classifier2.cv_results_)
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000650,0.000244,0.001125,0.000217,auto,euclidean,5,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
1,0.000517,0.000030,0.001018,0.000091,auto,euclidean,10,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,1
2,0.000642,0.000226,0.001034,0.000112,auto,euclidean,15,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,7
3,0.000497,0.000015,0.001068,0.000164,auto,euclidean,25,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,10
4,0.000519,0.000052,0.001087,0.000173,auto,manhattan,5,"{'algorithm': 'auto', 'metric': 'manhattan', '...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,9
5,0.000483,0.000020,0.000935,0.000021,auto,manhattan,10,"{'algorithm': 'auto', 'metric': 'manhattan', '...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
6,0.000529,0.000039,0.001066,0.000111,auto,manhattan,15,"{'algorithm': 'auto', 'metric': 'manhattan', '...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
7,0.000483,0.000019,0.000962,0.000034,auto,manhattan,25,"{'algorithm': 'auto', 'metric': 'manhattan', '...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,10
8,0.000507,0.000027,0.001034,0.000105,auto,minkowski,5,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
9,0.000504,0.000041,0.000959,0.000051,auto,minkowski,10,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,1
10,0.000534,0.000081,0.001020,0.000091,auto,minkowski,15,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,7
11,0.000476,0.000010,0.000964,0.000049,auto,minkowski,25,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,10

In [283]:
result2[['param_n_neighbors', 'param_metric', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

    param_n_neighbors param_metric  mean_test_score
1                  10    euclidean         0.980000
9                  10    minkowski         0.980000
0                   5    euclidean         0.973333
5                  10    manhattan         0.973333
6                  15    manhattan         0.973333
8                   5    minkowski         0.973333
2                  15    euclidean         0.966667
10                 15    minkowski         0.966667
4                   5    manhattan         0.960000
3                  25    euclidean         0.960000
7                  25    manhattan         0.960000
11                 25    minkowski         0.960000

In [284]:
result2[result2['mean_test_score'] == result2['mean_test_score'].max()]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
1,0.000517,0.000030,0.001018,0.000091,auto,euclidean,10,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.966667,1.0,1.0,0.933333,1.0,0.98,0.026667,1
9,0.000504,0.000041,0.000959,0.000051,auto,minkowski,10,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,1.0,1.0,0.933333,1.0,0.98,0.026667,1

# lets use the Random Search CV

model_svc

In [285]:
from sklearn.model_selection import RandomizedSearchCV
Classifier_r = RandomizedSearchCV(model_svc, {
    'gamma': ['auto'],
    'C': [1, 10, 20, 25, 30],
    'kernel': ['linear', 'rbf']
    }, 
    n_iter=5, cv=5, return_train_score=False)

In [286]:
Classifier_r.fit(X, y)
Classifier_r

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 25, 30],
                                        'gamma': ['auto'],
                                        'kernel': ['linear', 'rbf']})

In [287]:
result_r = pd.DataFrame(Classifier_r.cv_results_)
result_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_gamma,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000701,0.000142,0.000541,0.000108,rbf,auto,30,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,5
1,0.000551,0.000041,0.000421,0.000016,rbf,auto,10,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000600,0.000100,0.000447,0.000053,linear,auto,1,"{'kernel': 'linear', 'gamma': 'auto', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000572,0.000075,0.000459,0.000054,linear,auto,20,"{'kernel': 'linear', 'gamma': 'auto', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
4,0.000553,0.000017,0.000441,0.000020,rbf,auto,25,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 25}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3

In [288]:
result_r[['param_C', 'param_kernel', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

   param_C param_kernel  mean_test_score
1       10          rbf         0.980000
2        1       linear         0.980000
4       25          rbf         0.966667
3       20       linear         0.966667
0       30          rbf         0.960000

model_knn

In [289]:
from sklearn.model_selection import RandomizedSearchCV
Classifier_r2 = RandomizedSearchCV(model_knn, {
    'algorithm': ['auto'],
    'n_neighbors': [5, 10, 15, 25],
    'metric': ['euclidean', 'manhattan', 'minkowski']
    }, 
    n_iter=6, cv=5, return_train_score=False)

In [290]:
Classifier_r2.fit(X, y)
Classifier_r2

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=6,
                   param_distributions={'algorithm': ['auto'],
                                        'metric': ['euclidean', 'manhattan',
                                                   'minkowski'],
                                        'n_neighbors': [5, 10, 15, 25]})

In [291]:
result_r2 = pd.DataFrame(Classifier_r2.cv_results_)
result_r2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_metric,param_algorithm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000641,0.000195,0.001216,0.000358,5,minkowski,auto,"{'n_neighbors': 5, 'metric': 'minkowski', 'alg...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,2
1,0.000492,0.000032,0.001058,0.000135,10,manhattan,auto,"{'n_neighbors': 10, 'metric': 'manhattan', 'al...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2
2,0.000523,0.000035,0.001040,0.000098,15,euclidean,auto,"{'n_neighbors': 15, 'metric': 'euclidean', 'al...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,5
3,0.000504,0.000009,0.000970,0.000026,10,minkowski,auto,"{'n_neighbors': 10, 'metric': 'minkowski', 'al...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,1
4,0.000564,0.000081,0.001020,0.000055,15,manhattan,auto,"{'n_neighbors': 15, 'metric': 'manhattan', 'al...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2
5,0.000498,0.000004,0.000989,0.000005,25,minkowski,auto,"{'n_neighbors': 25, 'metric': 'minkowski', 'al...",0.933333,0.966667,0.933333,0.966667,1.0,0.960000,0.024944,6

In [292]:
result_r2[['param_n_neighbors', 'param_metric', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

   param_n_neighbors param_metric  mean_test_score
3                 10    minkowski         0.980000
0                  5    minkowski         0.973333
1                 10    manhattan         0.973333
4                 15    manhattan         0.973333
2                 15    euclidean         0.966667
5                 25    minkowski         0.960000